<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SingleFile.App</AssemblyName>
    <RootNamespace>SingleFile.App</RootNamespace>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Deterministic>true</Deterministic>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <ProjectReference Include="..\SingleFile.Dependency\SingleFile.Dependency.csproj" />
  </ItemGroup>
</Project>
